services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - RADICALE_URL=http://radicale:5232
    depends_on:
      - radicale
    networks:
      - app-network

  radicale:
    image: tomsquest/docker-radicale:latest
    ports:
      - "5232:5232"
    volumes:
      - radicale_data:/data
      - ./radicale_config:/etc/radicale
    environment:
      - RADICALE_CONFIG_FILE=/etc/radicale/config
    networks:
      - app-network

volumes:
  radicale_data:


networks:
  app-network:
    driver: bridge
